# Generated by Django 6.0.7 on 2026-08-23 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Composite match score computed by matching_engine (0.0 to 1.0)')),
                ('score_breakdown', models.JSONField(default=dict, help_text='Granular factors e.g. {"urgency": 0.9, "proximity": 0.85, "verification": 1.0, ...}')),
                ('status', models.CharField(choices=[('proposed', 'Proposed Match'), ('confirmed', 'Confirmed / Allocated'), ('rejected', 'Rejected')], default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.need')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.resource')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'unique_together': {('need', 'resource')},
            },
        ),
    ]
