# Generated by Django 6.0.7 on 2026-08-23 06:30

import core.spatial_compat
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='Official vehicle registration number e.g. AS-01-AB-1234', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(help_text='e.g. 5-Ton Truck, 4x4 Pickup, Delivery Van, Relief Boat', max_length=30)),
                ('current_location', core.spatial_compat.FallbackSpatialField(blank=True, help_text='Real-time GPS coordinate from last ping', null=True)),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle / Available'), ('en_route', 'En Route'), ('delivered', 'Delivered'), ('unavailable', 'Unavailable / Maintenance')], default='idle', max_length=20)),
                ('operator', models.ForeignKey(help_text='Assigned transport operator', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
    ]
