# Generated by Django 6.0.7 on 2026-08-23 06:30

import core.spatial_compat
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('road_blocked', 'Road Blocked / Impassable'), ('high_risk_corridor', 'High Risk Corridor Alert'), ('delivery_delayed', 'Delivery Delayed'), ('disruption_predicted', 'Disruption Predicted by AI')], max_length=50)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical (Immediate Action)'), ('high', 'High (Within 6-12 hours)'), ('medium', 'Medium (Within 24-48 hours)'), ('low', 'Low (Routine)')], default='medium', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('channel', models.CharField(choices=[('sms', 'SMS Text Message'), ('push', 'Push Notification'), ('app', 'In-App Alert Banner')], default='app', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_geojson', models.JSONField(blank=True, help_text='OSRM route geometry GeoJSON', null=True)),
                ('estimated_delay_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('delivery_status', models.CharField(choices=[('matched', 'Matched / Pending Dispatch'), ('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('delivered', 'Delivered & Fulfilled'), ('delayed', 'Delayed / Rerouting')], default='matched', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', core.spatial_compat.FallbackSpatialField(blank=True, null=True)),
                ('condition_type', models.CharField(choices=[('road_status', 'Road Status / Obstruction'), ('rainfall', 'Rainfall (mm)'), ('temperature', 'Temperature (°C)'), ('traffic', 'Traffic Bottleneck'), ('crowd_level', 'Crowd / Gathering Level'), ('bin_fill', 'Waste / Bin Fill Level'), ('landslide_risk', 'Landslide / Flood Risk Score')], max_length=50)),
                ('value', models.CharField(help_text="e.g. 'blocked', '42mm', 'high', 'clear'", max_length=50)),
                ('risk_score', models.FloatField(blank=True, help_text='0.0 to 1.0 risk score calculated by AI model', null=True)),
                ('source', models.CharField(choices=[('field_report', 'Field Report'), ('weather_api', 'Weather API (IMD / OpenWeather)'), ('prediction_model', 'AI Prediction Model'), ('sensor', 'IoT Sensor / Automated Feed')], default='field_report', max_length=30)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Cachar, East Khasi Hills', max_length=100, unique=True)),
                ('state', models.CharField(help_text='e.g. Assam, Meghalaya', max_length=50)),
                ('boundary', core.spatial_compat.FallbackSpatialField(blank=True, help_text='District boundary polygon for choropleths', null=True)),
                ('centroid', core.spatial_compat.FallbackSpatialField(blank=True, help_text='Center coordinate for quick zoom/centering', null=True)),
                ('population', models.IntegerField(blank=True, help_text='District population for impact analysis', null=True)),
            ],
            options={
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('food', 'Food Supplies'), ('water', 'Drinking Water'), ('medicine', 'Medical Supplies & Medicines'), ('construction_material', 'Construction & Shelter Material'), ('agricultural_produce', 'Agricultural Produce & Seeds'), ('other', 'Other Essential Resource')], max_length=50)),
                ('location', core.spatial_compat.FallbackSpatialField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('critical', 'Critical (Immediate Action)'), ('high', 'High (Within 6-12 hours)'), ('medium', 'Medium (Within 24-48 hours)'), ('low', 'Low (Routine)')], default='medium', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(help_text='e.g. kg, units, packets, litres', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('food', 'Food Supplies'), ('water', 'Drinking Water'), ('medicine', 'Medical Supplies & Medicines'), ('construction_material', 'Construction & Shelter Material'), ('agricultural_produce', 'Agricultural Produce & Seeds'), ('other', 'Other Essential Resource')], max_length=50)),
                ('location', core.spatial_compat.FallbackSpatialField(blank=True, null=True)),
                ('quantity_available', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('verification_status', models.CharField(choices=[('verified_org', 'Verified Organization / Agency'), ('unverified', 'Unverified Individual / Provider')], default='unverified', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
