# Generated by Django 6.0.7 on 2026-08-24 13:54

import core.spatial_compat
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Gauhati Medical College & Hospital (GMCH)', max_length=200)),
                ('category', models.CharField(choices=[('hospital', 'Hospital & Medical Center'), ('govt_office', 'Government Sector & DC Office'), ('emergency_station', 'Emergency & Disaster Response Hub (SDRF/NDRF/Fire)'), ('relief_shelter', 'High-Ground Flood / Disaster Relief Shelter'), ('logistics_hub', 'Strategic Logistics Hub / FCI Food Storage Depot')], default='hospital', max_length=50)),
                ('facility_type', models.CharField(blank=True, default='', help_text='e.g. Tertiary Care Medical College, DC Office, 1st Bn NDRF', max_length=100)),
                ('state', models.CharField(help_text='e.g. Assam, Meghalaya', max_length=50)),
                ('location', core.spatial_compat.FallbackSpatialField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('contact_number', models.CharField(blank=True, default='', max_length=50)),
                ('emergency_helpline', models.CharField(blank=True, default='', max_length=50)),
                ('bed_capacity', models.IntegerField(blank=True, default=0, help_text='Hospital bed count or shelter capacity', null=True)),
                ('is_auto_ingested', models.BooleanField(default=True, help_text='True if automatically ingested from public APIs (OSM / Govt Registry)')),
                ('source_api', models.CharField(default='osm_overpass', help_text='e.g. osm_overpass, nhm_registry, sdma_feed', max_length=50)),
                ('operational_status', models.CharField(choices=[('operational', 'Operational / Active'), ('partially_functional', 'Partially Functional'), ('flooded_impaired', 'Flooded / Impaired Access'), ('offline', 'Offline / Evacuated')], default='operational', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional JSON metadata (oxygen plant, ICU beds, emergency power, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='core.district')),
            ],
            options={
                'ordering': ['state', 'category', 'name'],
            },
        ),
    ]
